# Ruff configuration file for HarmonyDagger

# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B", "I", "W"]

# Never enforce line length violations (`E501`)
ignore = ["E501"]

# Target Python 3.8+
target-version = "py38"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow imports relative to the "harmonydagger" package
src = ["harmonydagger"]

[format]
# Use double quotes for strings.
quote-style = "double"

# Indent with 4 spaces.
indent-style = "space"
line-ending = "auto"

[isort]
known-first-party = ["harmonydagger"]

[lint.per-file-ignores]
# Allow star imports in __init__.py files
"**/__init__.py" = ["F401", "F403"]
